### ISSUE TITLE
Deprecation warning in 2024.7.0

### ISSUE THREAD

**Issue by lionslair** [TimSoethout/goodwe-sems-home-assistant#110]
Just posting here as the current ha release is logging a deprecation warning

`
Detected that custom integration 'sems' calls async_forward_entry_setup for integration, sems with title: 4327c190-4d32-4b56-ab83-514a5c23946c and entry_id: 438ba8a55baf5ff94d9efa219cf00c18, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/sems/__init__.py, line 37: hass.async_create_task(, please create a bug report at https://github.com/TimSoethout/goodwe-sems-home-assistant/issues

`

May be a HACS thing https://github.com/hacs/integration/issues/3850

**Comment by berkavil** [comment]
+1 here, the same warning with announced "this will stop working" flag...
thx if any clue.
W.
