### ISSUE TITLE
Format of variables

### ISSUE THREAD

**Issue by FreekBos** [TimSoethout/goodwe-sems-home-assistant#15]
Hi there, thanks for writing this integration.
I have a small/tiny question: 
      pv_iday:
        value_template: '{{ states.sensor.sems_portal.attributes.iday }}'
        unit_of_measurement: '€'
        friendly_name: "PV income day"
Gives an output of many many characters.
How can I format the output to say ###,## (e.g. for currency)
Thanks a mil,
F

**Comment by TimSoethout** [comment]
I'm not sure. This seems like a home assistant feature. Maybe you have more
luck at the home assistant forum? Or in the topic there about goodwe
inverters.
