### ISSUE TITLE
Show excess power available

### ISSUE THREAD

**Issue by dmshimself** [TimSoethout/goodwe-sems-home-assistant#21]
Extra useful template - I popped the following in so that I could use it to signal if power over that being used was available:

  pv_excess:
        value_template: '{{ states.sensor.sems_portal.attributes.pmeter }}'
        unit_of_measurement: 'W'
        friendly_name: "PV spare"

**Comment by TimSoethout** [comment]
Thanks.
Added it to the examples in the readme: https://github.com/TimSoethout/goodwe-sems-home-assistant/commit/0295dc9d3f4305ce9c63feca7a8399acfcda0e38
