### ISSUE TITLE
HACS SEMS Warning

### ISSUE THREAD

**Issue by Ascariota** [TimSoethout/goodwe-sems-home-assistant#23]
You are using a custom integration for sems which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
19:15:36 – loader.py (WARNING)

But working perfectly - Thank you for you works

**Comment by TimSoethout** [comment]
Thanks!
I think that message is there for all integrations not directly packaged with home assistant and thus all HACS components. I don't think we can get rid of it short of getting the add-on into the official HA integrations repo.
