### ISSUE TITLE
When sun goes down PV sensor does not go to 0 Watt

### ISSUE THREAD

**Issue by lukaskrepel** [TimSoethout/goodwe-sems-home-assistant#24]
Hi, thanks for the sensor!

When the sun goes down the PV power sensor does not go to 0 Watt, but instead hangs on the last measured value.

**Comment by spockz** [comment]
I have this issue as well on the SEMS portal. I assume it is a bug on the api side where it keeps using the latest reported value in case of a missed shutdown message from the PV. (The last part is speculation.)

**Comment by TimSoethout** [comment]
We could divert from the API output by overwrite the PV power sensor to `0`
when the inverter is off (found in another attribute). However, I don't
know if this is correct in all cases, e.g. if you have batteries?

**Comment by lukaskrepel** [comment]
Sounds like a good solution for my case! I don't have a battery...
I would assume the output would be zero for PV even with batteries, but I am not familiar with the SEMS portal API.

**Comment by lukaskrepel** [comment]
By the way: My current solution is to manually restart HA when the sun sets. The sensor goes to zero Watts. So I think the API simply doesn't respond when there's no power?

**Comment by TimSoethout** [comment]
In version 3.1.0 I added a check to report 0W when `status` is not `1`. :)
