### ISSUE TITLE
HA 2021.3.0 requests version manifest

### ISSUE THREAD

**Issue by pvmil** [TimSoethout/goodwe-sems-home-assistant#25]
As described in releasenotes of HA 2021.3.0, a version number is required in the manifest file: 
https://www.home-assistant.io/blog/2021/03/03/release-20213/#read-more
Could you please add this? Thanks for this very nice plugin, use it with much pleasure!

Output HA log:
Logger: homeassistant.loader
Source: loader.py:802
First occurred: 17:32:12 (2 occurrences)
Last logged: 17:32:13

No 'version' key in the manifest file for custom integration 'sems'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'sems'

**Comment by Ascariota** [comment]
I have the same :(

**Comment by TimSoethout** [comment]
Thanks for mentioning. I added a version to the manifest and hope it works. (Did not test yet.)

**Comment by pvmil** [comment]
Tested, this works, thnx!
