### ISSUE TITLE
Make update interval configurable

### ISSUE THREAD

**Issue by TimSoethout** [TimSoethout/goodwe-sems-home-assistant#29]

**Comment by jwolbink** [comment]
Hello Tim, After upgrade I only see the Inverter but not the other sensors. Please let me know how to solve it. Greetings , Johan.

**Comment by TimSoethout** [comment]
Hallo Johan, 
I guess this is not really related to this specific issue, but which other sensors do you mean?
The templates as mentioned in the readme should also be updated in your `application.yaml` since the sensor name/id is different. Does this help?

**Comment by jwolbink** [comment]
In the integration i see only one entity (sensor.inverter........). I'm missing the outputpower, tempperature, eday, etotal etc. I'm new so maybe it's not much what i'm doing wrong.

**Comment by TimSoethout** [comment]
Hi, if you open the entity, the other fields shoeld be visible as attributes:
![image](https://user-images.githubusercontent.com/593132/115963605-53e53980-a520-11eb-81d6-af963f1f1680.png)

**Comment by jwolbink** [comment]
Yes, Thats correct. How can I see some of this values in HA ?

**Comment by TimSoethout** [comment]
You need to replace $NAME with the name of your sensor. The `sensor.sems_portal` you mention no longer exists, since we support multiple inverters now.  Look in `http://.../config/entities` for you entity and use the new sensor id. :) Hope it works.

**Comment by TimSoethout** [comment]
@nickh66, update interval should now be configurable in config flow.

**Comment by TimSoethout** [comment]
I'll release a new release if it works for you.

**Comment by jwolbink** [comment]
> You need to replace `$NAME` with the name of your sensor. The `sensor.sems_portal` you mention no longer exists, since we support multiple inverters now. Look in `http://.../config/entities` for you entity and use the new sensor id. :) Hope it works.

> I have replace   $NAME . What do tou mean with: Look in `http://.../config/entities` for you entity and use the new sensor id ?

> btw. please open a new issue, if this doesn't work.
> 
> This issue actually for a different feature request. ;)

**Comment by TimSoethout** [comment]
Released as version 3.2.0
