### ISSUE TITLE
Monthly amount

### ISSUE THREAD

**Issue by wauwturrr** [TimSoethout/goodwe-sems-home-assistant#32]
Hi Tim,

Is it also possible to read out the monthly production of the solar-panels?

**Comment by TimSoethout** [comment]
I'm not sure. If it is available on semsportal.com we should be able to get it as well.

Otherwise you can calculate it yourself in HA probably.

**Comment by TimSoethout** [comment]
Also  in the attributes I see:
```
Thismonthetotle
280.5
Lastmonthetotle
5772
```

I guess that could be what your looking for?

**Comment by wauwturrr** [comment]
Works like a charm, thanks!
