### ISSUE TITLE
 The custom integration 'sems2mqtt' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

### ISSUE THREAD

**Issue by antoinevandenhurk** [TimSoethout/goodwe-sems-home-assistant#35]
The version key is required from Home Assistant version 2021.6. Is there going te be an update for this matter?

**Comment by TimSoethout** [comment]
Sure, feel free to add it. :)
I'm always a bit behind with updating HASS, so free to already do it in a
pull request.

**Comment by TimSoethout** [comment]
@antoinevandenhurk , it seems that this is not an issue for this plugin, but for `sems2mqtt`.  Maybe consider reporting there: https://github.com/bouwew/sems2mqtt.

If this is also a problem here, please reopen the issue. :)
