### ISSUE TITLE
Attributes show unavailable

### ISSUE THREAD

**Issue by Robje007** [TimSoethout/goodwe-sems-home-assistant#38]
My added attributes are not working they are all showing as unavailable, I replaced $NAME with Goodwe (Thats how it is called in Home assistant)

This is an example of the first attribute in my configuration.yaml:

sensor: 
    platform: template
   sensors:
    pv_outputpower:
    value_template: '{{ states.sensor.inverter_Goodwe.attributes.outputpower }}'
    unit_of_measurement: 'W'
    friendly_name: "PV Power output"

**Comment by TimSoethout** [comment]
Hmm... That's odd. Anything in the log from SEMS?

You can also try the template on: http://hassio.lan:8123/developer-tools/template (replace your host name).
What does it show there?

**Comment by Robje007** [comment]
Thanks for the suggestion
I used the (friendly) name instead of the entity-id, solved!
