### ISSUE TITLE
last_reset attribute for new energy entity not getting set properly

### ISSUE THREAD

**Issue by kaizersoje** [TimSoethout/goodwe-sems-home-assistant#47]
I noticed the `last_reset `attribute for the newly created energy entity does not seem to be changing. Is this as expected?

![image](https://user-images.githubusercontent.com/54566217/129281185-eb6a4ba8-08ce-4780-a975-14a6955ff7f7.png)

**Comment by TimSoethout** [comment]
Seems to be fine: https://developers.home-assistant.io/docs/core/entity/sensor/#properties
It's the total kWh for your inverter, which only grows, so the specific start time is not important.
Reset if for power meter for example that reset when installing a new one or something.

Feel free to make a pull request if you want to use a more sane/recent value there.
