### ISSUE TITLE
Error " unexpected state class "  for sensor since homeasstant 2021.9

### ISSUE THREAD

**Issue by tabnul** [TimSoethout/goodwe-sems-home-assistant#49]
Since last update of home assistant (2021.9) , things seem to have changed for energy sensors.
I get below error for the SEMS sensor (also for all other energy logging sensors)

Unexpected state class
The following entities do not have the expected state class 'total_increasing'

![image](https://user-images.githubusercontent.com/16493960/131977523-8156da19-d273-4306-81c5-7f8d3feb5209.png)

**Comment by gvssr** [comment]
Getting the same error on 2021.9.2

**Comment by TimSoethout** [comment]
That is odd. I scanned the new documentation and `measure` sensor should not need this new property.
I will fix it when I have time to upgrade my HA version, which might take a while.

**Comment by Jozziej** [comment]
> That is odd. I scanned the new documentation and `measure` sensor should not need this new property. I will fix it when I have time to upgrade my HA version, which might take a while.
> […](#)
> On September 3, 2021 11:31:06 PM GMT+02:00, gvssr ***@***.***> wrote: Getting the same error on 2021.9.2 -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#49 (comment)](https://github.com/TimSoethout/goodwe-sems-home-assistant/issues/49#issuecomment-912821571)

Hi Tim,

I see you just commited a change, I also manually did the same manually on my end and it works.

Below import can also be removed now if i'm not mistaken
"from homeassistant.util.dt import utc_from_timestamp"

**Comment by TimSoethout** [comment]
Eventually yes, but the `last_reset` is still there. I guess we can remove it too.

**Comment by TimSoethout** [comment]
Removed it now in a new commit. Feel free to try the `master` branch.

**Comment by Jozziej** [comment]
Ok yes, I also tried it on my end without the last reset, since it's already deprecated now.

**Comment by TimSoethout** [comment]
Released in 3.4.0
