### ISSUE TITLE
Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11

### ISSUE THREAD

**Issue by MPowerData** [TimSoethout/goodwe-sems-home-assistant#54]
Hi,

Since the latest upgrade of Home Assistant below warning is showing up in the log.

WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.inverter_gw3600d_ns_energy (<class 'custom_components.sems.sensor.SemsStatisticsSensor'>) with state_class measurement has set last_reset. Setting last_reset is deprecated and will be unsupported from Home Assistant Core 2021.11. Please update your configuration if state_class is manually configured, otherwise report it to the custom component author.

Is this something I can fix?

Or does the integration need an update?

Thanks for your help.

**Comment by TimSoethout** [comment]
The latest version should not have `last_reset` anymore. Did you update the component?

**Comment by MPowerData** [comment]
Hmmm, how do I run the update?

**Comment by TimSoethout** [comment]
Via HACS?
Or copy the files from this repo to your `custom_components` directory.

**Comment by MPowerData** [comment]
Thanks, that worked!
