### ISSUE TITLE
Negative power

### ISSUE THREAD

**Issue by TonKro** [TimSoethout/goodwe-sems-home-assistant#63]
Lately while the solar is not active I get high kwh peaks back. Some times later these peaks are "equalized" with a negative peak:

![image](https://user-images.githubusercontent.com/65308845/147734039-be580425-0f1d-4653-ba63-9c6023f2b670.png)

![image](https://user-images.githubusercontent.com/65308845/147734144-a2a989fd-6290-4af4-a3fa-fd0ee084d6ae.png)

I also have an API running in node-red there this is not happening. It only does happen in Home Assistant.

![image](https://user-images.githubusercontent.com/65308845/147734407-47b611bb-2607-402a-b72b-d2858b506799.png)

What could cause this and how can I solve it?

Some further looking is that the future day also does have data already, but in the night:

![image](https://user-images.githubusercontent.com/65308845/147739801-f1f573ff-9564-4559-a7ac-888c16e738f2.png)

Date and time of the machine is correct.

**Comment by TimSoethout** [comment]
That is really odd... The energy should be an always increasing unit. We take the `data["etotal"]` from the API, so that seems to return different values (older? or of the other inverter?) for you somehow.

**Comment by TonKro** [comment]
There are not more then the 3 showed inverters. I do not get it either, but somehow as the problem did appear it did disappear. For now let's close the issue, I will keep a close eye on it.

Thanks a lot.

**Comment by TimSoethout** [comment]
If it happens again you can try turning on debug logging. It should log the JSON from the API as well. See the readme on how to do this.
Good luck!
