### ISSUE TITLE
data is not updated

### ISSUE THREAD

**Issue by byjosemaria** [TimSoethout/goodwe-sems-home-assistant#7]
Hello, I have installed this component in Hassio and the data is not updated, only if I restart Hassio makes a new reading of the data. regards

**Comment by TimSoethout** [comment]
Hi, that is odd. I do have sometimes that it looses connection to the SEMS portal and then a restart of home assistant makes is work again.

Do you mean you get a new single data point when restarting? I think that is just the last known value, and not really fresh data. 
Does your home assistant log say anything? You should be able to see that on the `http://hassio:8123/dev-info` page.

**Comment by byjosemaria** [comment]
Hello
It was my mistake. It works perfectly. 
I was confused when I checked the time the sensor was always increasing, I thought it was reset every time I updated the data with the SEMS portal.
Thanks and regards

**Comment by TimSoethout** [comment]
NP, glad it is working!
