### ISSUE TITLE
$Name - how to use? 

### ISSUE THREAD

**Issue by Hufflepuff-source** [TimSoethout/goodwe-sems-home-assistant#72]
You shared a sample config on retrieving more data. 

Can you show me an example on how to the $Name is used? 

My entity id is sensor.inverter_inverter. 
so will the line look like - value_template: '{{ states.sensor.inverter_inverter_inverter.attributes.tempperature }}'?

**Comment by TimSoethout** [comment]
`{{ states.sensor.inverter_inverter.attributes.tempperature }}` I would guess. But please try it out. :)

You can also try out templates at: `http://hassio.lan:8123/developer-tools/template` (change host to your HA instance)
