### ISSUE TITLE
SEMS API show only two devices an 4 entities

### ISSUE THREAD

**Issue by matusrajnoha** [TimSoethout/goodwe-sems-home-assistant#77]
<img width="318" alt="Snímka obrazovky 2022-10-13 o 18 19 54" src="https://user-images.githubusercontent.com/109215057/195651401-9f4a1730-a35b-4339-a281-61a99bc9f9de.png">

Please, how to resolve?

**Comment by TimSoethout** [comment]
What did you expect? Each inverter has 2 entities.

13 Oct 2022 18:20:53 matusrajnoha ***@***.***>:

**Comment by matusrajnoha** [comment]
I can see a lot of entities over a local connection. In the past I also had them through the SEMS API
<img width="303" alt="Snímka obrazovky 2022-10-13 o 21 39 45" src="https://user-images.githubusercontent.com/109215057/195694059-afb9abc4-f815-40e9-a270-1e3a59c83163.png">

**Comment by TimSoethout** [comment]
The entities contain the values as attributes.

13 Oct 2022 21:41:54 matusrajnoha ***@***.***>:

**Comment by matusrajnoha** [comment]
The question was why I don't have them there when they were there.

**Comment by TimSoethout** [comment]
They were there when using the local component if I understand you correctly. That is a different component which works differently. Maybe if you use that one again they will return?

This component is fetching the data via the cloud API. The other one, which is included in HA, uses the local network directly to the inverter.

Is this the issue?

13 Oct 2022 22:20:23 matusrajnoha ***@***.***>:

**Comment by matusrajnoha** [comment]
Yes, it's a problem. I didn't use the local component because of the floods. Entities and sensors were available. Now for some reason they don't. You state this, see photo.
<img width="471" alt="Snímka obrazovky 2022-10-14 o 15 50 36" src="https://user-images.githubusercontent.com/109215057/195863710-78e4f3a5-3626-4051-b36d-eab5f3f3ea31.png">

**Comment by TimSoethout** [comment]
Yes, the photo shows attributes, not separate entities. The screenshot is old so maybe the UI looks different now, but the attributes are still there. :)
