### ISSUE TITLE
How to enter the SEMS ID user/pass information

### ISSUE THREAD

**Issue by bradpraz** [TimSoethout/goodwe-sems-home-assistant#80]
I've had to restart my HA setup and I'm adding this intergration via HACS. Last time I did it a window popped up to enter the SEMS ID and user/pass now I can't seem to find where to enter that. 
![image](https://user-images.githubusercontent.com/122725814/219900977-1425611f-dffa-468e-bda6-cfe7babc4330.png)
Can anyone tell me how to enter this information?

**Comment by TimSoethout** [comment]
Settings > Devices & Services > Add Integration (bottom right corner)

**Comment by bradpraz** [comment]
Thankyou, missed that step still learning HA.
