### ISSUE TITLE
New user Looking for Export Data - is it true this only exposes two sensors?

### ISSUE THREAD

**Issue by old-square-eyes** [TimSoethout/goodwe-sems-home-assistant#81]
Great project BTW!

I'm a bit of a noob so sorry if my termanology is off or I missed something. I was able to add HACS, and then SEMS to my Home Assistant Docker setup and see only "Total Generation" and "Current Generation" from my Goodwe panels.

I would like to automate my GPU mining rig based on Nicehash (yes I know GPU mining is dead) to only mine when I am generating excess energy.

The easiest way to accurately trigger that is to periodiacally monitor at a threshold when I'm pushing to, and pulling from the grid.

How can I bring the grid import/export grid attribute in to further process this info?

**Comment by old-square-eyes** [comment]
Actually I see some import and export figures under Homekit. What are these? They don't match my Goodwe SEMS mobile app and are measured in kWh.

**Comment by midadami** [comment]
SEMS works badly from time to time. It has several minutes delay when it works badly. It has months without problems but since yesterday its again failing.

**Comment by old-square-eyes** [comment]
> SEMS works badly from time to time. It has several minutes delay when it works badly. It has months without problems but since yesterday its again failing.

Wait so I should be able to see more data ordinarily?

**Comment by midadami** [comment]
> > SEMS works badly from time to time. It has several minutes delay when it works badly. It has months without problems but since yesterday its again failing.
> 
> Wait so I should be able to see more data ordinarily?

Under current generation you can see all the inverter attributes when it works correctly. SEMS not working correctly for me now.

**Comment by TimSoethout** [comment]
What @midadami says indeed. In the readme (https://github.com/TimSoethout/goodwe-sems-home-assistant#screenies) you see a screenshot of some of the attributes. There are more when you scroll down at your own instance.
Hopefully there is an attribute there that you can use for your purpose.

**Comment by old-square-eyes** [comment]
I'm pretty confused then. I see nothing like the screen shot. I see the below.

![image](https://user-images.githubusercontent.com/25760491/221375250-f414c4c6-b827-41f2-a28b-e8947ff179ce.png)

**Comment by old-square-eyes** [comment]
Clicking into the graphs only gives me timelines of the existing metrics,...

![image](https://user-images.githubusercontent.com/25760491/221375385-c16764d8-1be3-4949-8dce-ce329b01b8a4.png)

**Comment by TimSoethout** [comment]
> Clicking into the graphs only gives me timelines of the existing metrics,...
> 
> ![image](https://user-images.githubusercontent.com/25760491/221375385-c16764d8-1be3-4949-8dce-ce329b01b8a4.png)

Click on `Attributes` in the lower right of the picture. :)

**Comment by old-square-eyes** [comment]
I see it now. Not sure if I missed it before or if it wasn't there. Thanks! Not sure which one's export but I'll find it I'm sure.

**Comment by old-square-eyes** [comment]
FYI for anyone else I used this to set up a sensor for the attribute values...

https://community.home-assistant.io/t/lovelace-ui-gauge-card-add-attribute-variable/311634/3

<img width="394" alt="image" src="https://user-images.githubusercontent.com/25760491/221380953-7510492b-2f35-4fa8-8659-88a4601aef56.png">

This is great!
